version: "3.8"

services:
  server:
    image: nginx:stable-alpine
    ports: 
      - '8003:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - '8004:80'
    environment:
      - PMA_ARBITRARY=1
  react:
    image: node:14
    working_dir: /app
    volumes:
      - ./react-fe/go-dutch-fe:/app
    ports:
      - '3003:3000'
    command: bash -c "npm install && npm start"
    depends_on:
      - server
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html
volumes:
  mysql_data:
    driver: local
