apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: src
              mountPath: /usr/share/nginx/html
      volumes:
        - name: src
          emptyDir: {}
---
apiVersion: v1
kind: Deployment
metadata: 
  name: php
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
